metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: nginx
  metricsets: 
    - "stubstatus"
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://localhost"]

  # Path to server status. Default server-status
  server_status_path: "server-status"

# - module: elasticsearch
#   metricsets:
    # - node
    # - node_stats
    # - index
    #- index_recovery
    #- index_summary
    #- shard
    #- ml_job
  # period: 10s
  # hosts: ["http://localhost:9200"]
  #username: "elastic"
  #password: "changeme"

  # Set to false to fetch all entries
  #index_recovery.active_only: true

  # Set to true to send data collected by module to X-Pack
  # Monitoring instead of metricbeat-* indices.
  #xpack.enabled: false


output.elasticsearch:
  hosts: ["http://elasticsearch"]
  # pipeline: geoip-info

